### ISSUE TITLE
[BUG] EXC log errors

### ISSUE THREAD

**Issue by zer0Kerbal** [net-lisias-ksp/ModuleManager#18] opened 2023-01-09 04:50 UTC
FYI experienced during scene change(s) flight--> KSC --> editor

```
18619 [EXC 22:36:35.501] FormatException: Input string was not in a correct format.
18624     UnityEngine.DebugLogHandler:LogException(Exception, Object)
18625     KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
18626     ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)

18875 [EXC 22:36:48.748] FormatException: Input string was not in a correct format.
18880     UnityEngine.DebugLogHandler:LogException(Exception, Object)
18881     KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
18882     ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)

19408 [EXC 22:44:41.708] FormatException: Input string was not in a correct format.
19413     UnityEngine.DebugLogHandler:LogException(Exception, Object)
19414     KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
19415     ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)

19616 [EXC 22:44:52.609] NullReferenceException: Object reference not set to an instance of an object
19619     UnityEngine.DebugLogHandler:LogException(Exception, Object)
19620     KSPe.Util.Log.UnityLogDecorator:UnityEngine.ILogHandler.LogException(Exception, Object)
19621     ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
19622     UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

[KSP.zip](https://github.com/net-lisias-ksp/KSPe/files/10370411/KSP.zip)

just updated to KSPe 2.4.2.8, was experiencing it prior to updating as well.

**Comment by Lisias** [comment] 2023-01-11 13:03
Remove the "bug", as it's not a bug from my side. Added support for obvious reasons.

Add `environment-problem` because, in the end, it's a problem on a code being compiled in C#6 and then trying to be ran on a .NET 4.5 environment!

**Comment by Lisias** [comment] 2023-05-21 23:28
Closing this, as I think the problem was fixed on the reporter's side.

**Closed by Lisias** 2023-05-21 23:28 UTC
Labels: environment-problem, support, unrelated
