### ISSUE TITLE
Duplicate modulemanager.dll 

### ISSUE THREAD

**Issue by stk2008** [net-lisias-ksp/ModuleManager#17] opened 2022-11-10 15:21 UTC
Hi I wanted to give this version of modulemanager a go and I am getting a warning from ZeroMiniAVC saying there is two identicle modulemanager DLL files.

gamedata
....................modulemanager.dll
other is
gamedata
...................ModuleManager
.....................................................PluginData
...........................................................................modulemanager.dll

have i installed correctly or should ZeroMiniAVC  not worry about it if that is the case and both dll files are reqiured I think ZeroMiniAVC ignores one of them so will this cause issues?

Thanks in advance :)

**Comment by Lisias** [comment] 2022-11-10 22:43
Hi!

The ZeroMiniAVC is wrong. The DLL in the PluginData is not loaded by KSP, it's meant to be used as a reference so ModuleManager WatchDog knows if anyone messed up the one being in used.

As it appears, I will need to declare ZeroMiniAVC incompatible. DAMN.

**Comment by stk2008** [comment] 2022-11-10 23:11
Thanks for the reply.
so on the forum post it does say it prunes one of them https://forum.kerbalspaceprogram.com/index.php?/topic/174445-112x-malahs-quick-mods-important-update-for-zerominiavc/

https://i.imgur.com/bwA6q8L.png

I got a pop up saying about duplicates but clicked ignore and the game seems to run fine...infact my game seems a bit more stable with your module manager installed+KSP API so I am unsure at what point there could be an issue?.
I also noticed the same thing with infernal robotics that also ships with a scale.dll but I was under the impression I should delete the one in infernal robotics and let tweakscales scale.dll be the only one was zero mini AVC wrong in telling me to remove one of them also?

**Comment by Lisias** [comment] 2022-11-10 23:16
That's the problem: you can't have two DLLs with the same name **being loaded** by KSP, but anything inside `PluginData` is not loaded by KSP, so should not be checked at all.

ZeroMiniAVC is messing with 3rd parties code internal business.

Right now I'm considering if I just rename these reference files to something else (what's kinda of obfuscation), or if I get rid of ZeroMiniAVC for good and declare it incompatible with MM WatchDog (and by side effect, KSP-Recall and TweakScale) and do the job on the WatchDog, and so prevent more external interference on my add'ons.

**Comment by Lisias** [comment] 2022-11-10 23:19
The way this goes, ZeroMiniAVC will trigger spurious warnings to anyone loading custom DLLs from PluginData that have the bad look of clashing with something from a completely unrelated 3rd party.

Consider an addon that uses his own custom compilation for, let's see, ProtoBuffer. And it loads if from PluginData, to avoid screwing up someone with a default version of ProtoBuffer.

This guy would be flagged as soon as another add'on with another DLL named ProtoBuffer is installed.

And they should not.

DLL naming classes is a problem **only for DLLs loaded by KSP**, not by DLLs loaded by the add'on themselves.

**Comment by stk2008** [comment] 2022-11-10 23:27
Hmmm I wonder if this is some of the issues then why infernal robotics plays up for me I shall readd the scale.dll back to infernal robotics and temp remove zero mini AVC.
Thanks for taking the time to reply :)

**Comment by Lisias** [comment] 2022-11-11 05:18
> Hmmm I wonder if this is some of the issues then why infernal robotics plays up for me I shall readd the scale.dll back to infernal robotics and temp remove zero mini AVC. Thanks for taking the time to reply :)

If the DLL is inside a folder called `PluginData`, you should leaved it alone.

If DLL is outside a folder called `PluginData`, and it's also called `Scale.dll`, then this is a major bork of Infernal Robotics - but TweakScale would complain to you, and so you would know in a way or another.

I have the strict policy of not mangling with 3rd parties unless **strictly necessary**. And even by then, only on add'ons I have **positive** confirmation of needing such external intervention.

Preemptively messing with 3rd parties without a solid confirmation of that being needed is a serious no-no on my book and, frankly, it's one of the worst problems on KSP Scene.

**Comment by Lisias** [comment] 2022-11-11 05:21
> EDIT so looking at the zero mini avc mod it the setting you can turn off every thing so all it does is prune/delete only avc files so I shall do that. https://i.imgur.com/iIJY23R.png

That's the problem: you **want** to get rid of every MiniAVC*.dll on your system. At best, it's a annoyance - people willing to use the feature should install KSP-AVC instead, the MiniAVC is intrusive and, well, a privacy problem (it will ping a server somewhere identifying your IP - not to mention being a GDPR violation on Europe). At worst, older MiniAVC is known to cause **a lot** of crashes on KSP.

**Comment by stk2008** [comment] 2022-11-11 16:53
Thank you for explaining and sorting this out.
I have readded the DLL files back to there plugin folders within a few mods and disabled the checking of such files from zero mini avc and have it to only attack the miniavc files.

all the best :)

**Comment by Lisias** [comment] 2022-11-12 00:34
@stk2008 

> NM module manager watch dog is also complining of multiple scale.dll files so no idea

MMWD is conservative. If it barks, it really found something **proven** to be a problem.

Publish your KSP.log and I will check it. There's a chance you (or something else) had unzipper TweakScale more than once on your GameData.

**Comment by stk2008** [comment] 2022-11-12 01:03
:( i deleted the log file after I deleted the two scale.dll files from ferrum and infernal robotics :(.
I have been playing for a while now after that and I do get a lot of errors but tbh thats my own fault as I am running soooo many mods.I am trying to work my way through them all but I have no idea what I am doing.

this is the recent log file https://www.sendspace.com/file/e1fwtz but this is with as said above the scale.dll removed from ferrum aerospace and infernal robotics.

Is there a tool that will allow me to decipher the very vague (well for a none programmer any way) errors and what I can do to fix them.I am currently trying to track down what contract mod is causing spam.
I know your very very busy but if you did get a chance to peek at me logs to see if you can suggest ways to improve some of the issues that would be very very much appreciated.

All the best :)

**Comment by Lisias** [comment] 2022-11-13 18:31
@stk2008 

I found time to see your case only today, sorry being late.

I didn't found any duplicate `Scale_Redist` on the log you published - duplicated `Scale_Redist` assemblies were common in the past because earlier people used to just shove all their hard dependencies on the zip file and call it a day. KSP resented a bit this practice (as this creates many Application Domains inside the C# runtime and this slows everything), but since it didn't break KSP, people kept doing it.

On KSP 1.8 things changed in a way in which duplicated Assemblies are not loaded anymore, only "linked", and so no more new Application Domains screwing up performance. But this created another problems, and this is the reason I had to go nuclear on the `Scale_Redist` thingy.

ZeroMiniAVC is still barking on the wrong tree. Please ignore this one.

```
[WRN 22:30:13.639] ZeroMiniAVC started ...
[LOG 22:30:14.004] Duplicate DLLs found: C:/Kerbal Space Program/KSP_x64_Data/../GameData/ModuleManager.dll : C:/Kerbal Space Program/KSP_x64_Data/../GameData/ModuleManager\PluginData\ModuleManager.dll
```

What I found is that apparently you have a duplicated Scatterer on your rig:

```
[ERR 23:21:09.297] [Scatterer][Error] Destroying duplicate instance, check your install for duplicate scatterer folders, or nested GameData folders
```

But I only found one…

```
[LOG 22:29:32.229] Load(Assembly): scatterer/scatterer
[LOG 22:29:32.229] AssemblyLoader: Loading assembly at C:\Kerbal Space Program\GameData\scatterer\scatterer.dll
```

So there's something else happening on your rig that I can't see. I think you should reach the Scatterer folks and ask about.

**Comment by stk2008** [comment] 2022-11-13 18:43
Mate please dont be sorry you was under no obligation to look for me...I'm very very thankful. 
I shall take a look for scattered dupes.i will install agentransack and see if that can find duplicates. 

Thank you so much for looking.
P.s I see u have updated a few of your mods i shall be updating them to the latest tonight.

Thanks again

**Comment by fridgebro** [comment] 2022-12-31 12:52
Related for people who dont already know, older versions of module manager watch dog have the same bug.

**Comment by Lisias** [comment] 2023-01-01 05:58
> Related for people who dont already know, older versions of module manager watch dog have the same bug. If this persists after getting rid of zero mini AVC, update MMWD.

It's not a bug, it's a feature!! :D (seriously)

However, there's a bug on a thingy called `Assembly Loader/Resolver` that can be triggered by anyone trying to load a dependency and fails by some reason. Once this thing is triggered, **anything** trying to load another DLL or using a thingy called `Reflection` borks relentlessly - and MMWD makes heavy use of these two things.

Getting rid of older MiniAVC's DLL removes that trigger from the system, and so MMWD (and many others) come back to life because that AL/R bug is not bitting our arses anymore!

Cheers!

**Comment by Lisias** [comment] 2023-05-21 23:29
Forgot to close this! Doing it now!

**Closed by Lisias** 2023-05-21 23:29 UTC
Labels: support, unrelated
