### ISSUE TITLE
MM cannot parse values for some reason

### ISSUE THREAD

**Issue by Starcatcher2009** [net-lisias-ksp/ModuleManager#21] opened 2023-07-26 10:07 UTC
```
@Kopernicus:AFTER[SigDim2]
{
	@Body:HAS[#name[*]]
	{
		@Properties
		{
			mass = #$../Properties/geeASL$
			@mass *= 9.807

			radiusSquared = #$../Properties/radius$
			@radiusSquared != 2

			@mass *= #$../Properties/radiusSquared$
			@mass /= 6.674e-11

			!radiusSquared = DEL


			gravParameter = #$../Properties/mass$
			@gravParameter *= 6.674e-11
		}
	}
}
```

ModuleManager for some reason cannot parse radiusSquared and mass. Why is that?
Note: Before this was patched in the configs only existed geeASL and radius.

**Comment by Lisias** [comment] 2023-07-26 10:29
Check the ConfigCache and see that you get here. I think the problem is:

```
mass = #$../Properties/geeASL$
```

If there is already a `mass` attribute in the section, then the following multiplier will be applied to the first one. I think you should use:

```
%mass = #$../Properties/geeASL$
```

Same for `radiusSquared` and `gravParameter`.


Additionally… How many "Properties" sections there is on the original Config Section? It looks to me that you are going to the parent section and then back to the current `Property` section, but if by any reason there's another one on the parent, you may be getting the value from the wrong place. Perhaps using `#$/geeASL$` would be a better option?

Give a peek on [this post](https://forum.kerbalspaceprogram.com/topic/50533-18x-112x-module-manager-423-july-03th-2023-fireworks-season/?do=findComment&comment=3952536) on Forum.

**Comment by Lisias** [comment] 2023-07-27 13:24
Oukey. What I need to install in order to apply this patch?

Kopernicus for sure.

What's SigDim2? Where I download it?

**Comment by Lisias** [comment] 2023-07-28 00:07
Well, I give his a try - it happens that `SigDim2` is a symbol defined by Sigma Dimensions.

This is the result of your path:

```
[LOG 20:56:57.926] [ModuleManager] INFO: Applying update __LOCAL/TEST/@Kopernicus:AFTER[SigDim2] to Kopernicus/Config/System.cfg/Kopernicus[Kerbol System]
[LOG 20:56:57.927] [ModuleManager] INFO: variable search output : ="1.74684656100137"
[LOG 20:56:57.927] [ModuleManager] INFO: variable search output : ="261600000"
[LOG 20:56:57.927] [ModuleManager] WARNING: Cannot find key radiusSquared in Properties
[LOG 20:56:57.928] [ModuleManager] ERROR: Error - Cannot parse variable search when editing key mass = #$../Properties/radiusSquared$ at Log:0
[LOG 20:56:57.928] [ModuleManager] WARNING: Cannot find key mass in Properties
[LOG 20:56:57.929] [ModuleManager] ERROR: Error - Cannot parse variable search when inserting new key gravParameter = #$../Properties/mass$ at Log:0
```

There's no `radiusSquared` on the parent Section called `Properties`. This screwed up the `mass` definition later, and from that point `mass` also started to give you problems.

**Comment by Lisias** [comment] 2023-07-28 00:19
So I adapted the patch to include `%` for adding new attributes.

```
@Kopernicus:AFTER[SigDim2]
{
        @Body:HAS[#name[*]]
        {
                @Properties
                {
                        %mass = #$../Properties/geeASL$
                        @mass *= 9.807

                        %radiusSquared = #$../Properties/radius$
                        @radiusSquared != 2

                        @mass *= #$../Properties/radiusSquared$
                        @mass /= 6.674e-11

                        !radiusSquared = DEL

                        %gravParameter = #$../Properties/mass$
                        @gravParameter *= 6.674e-11
                }
        }
}
```

This change ensure that all attributes' parches will be executed at the same time (see the order in which patches are applied for reference).

And then I got this:

```
[LOG 21:15:39.401] [ModuleManager] INFO: Applying update __LOCAL/TEST/@Kopernicus:AFTER[SigDim2] to Kopernicus/Config/System.cfg/Kopernicus[Kerbol System]
[LOG 21:15:39.402] [ModuleManager] INFO: variable search output : ="1.74684656100137"
[LOG 21:15:39.402] [ModuleManager] INFO: variable search output : ="261600000"
[LOG 21:15:39.403] [ModuleManager] WARNING: Cannot find key radiusSquared in Properties
[LOG 21:15:39.403] [ModuleManager] ERROR: Error - Cannot parse variable search when editing key mass = #$../Properties/radiusSquared$ at Log:0
[LOG 21:15:39.404] [ModuleManager] WARNING: Cannot find key mass in Properties
[LOG 21:15:39.404] [ModuleManager] ERROR: Error - Cannot parse variable search when replacing (%) key gravParameter = #$../Properties/mass$ at Log:0
```

Same result. The problem is the absence of the attribute `radiusSquared` in Properties, and from that point everything else gets screwed.

**Comment by Lisias** [comment] 2023-07-28 01:01
@Starcatcher2009 , I'm an idiot! The problem is obvious!! :D

This patch will work:

```
@Kopernicus:AFTER[SigDim2]
{
	@Body:HAS[#name[*]]
	{
		@Properties
		{
			%mass = #$../Properties/geeASL$
			@mass *= 9.807

			%radiusSquared = #$../Properties/radius$
			@radiusSquared != 2

			@mass *= #$radiusSquared$
			@mass /= 6.674e-11

			!radiusSquared = DEL

			%gravParameter = #$mass$
			@gravParameter *= 6.674e-11
		}
	}
}
```

What is happening is that `mass`, `radiusSquared` and `gravParameter` are new values being created on the current new node that it's being build to replace the original, but it was not yet. So they do not exist in the original Node, only on the current "temp" one.

I had to read the original Config Node from Kopernicus in order to realize that, and even by doing it took me some test runs until "a ficha cair" (as we used to say around here).

**Comment by Lisias** [comment] 2023-07-28 01:03
Proof:

```
[LOG 22:00:44.491] [ModuleManager] INFO: Applying update __LOCAL/TEST/@Kopernicus:AFTER[SigDim2] to Kopernicus/Config/System.cfg/Kopernicus[Kerbol System]
[LOG 22:00:44.492] [ModuleManager] INFO: variable search output : ="1.74684656100137"
[LOG 22:00:44.492] [ModuleManager] INFO: variable search output : ="261600000"
[LOG 22:00:44.493] [ModuleManager] INFO: variable search output : ="6.843456E+16"
[LOG 22:00:44.493] [ModuleManager] INFO: variable search output : ="1.7566296605769E+28"
[LOG 22:00:44.493] [ModuleManager] INFO: variable search output : ="0.275093947318621"
[LOG 22:00:44.493] [ModuleManager] INFO: variable search output : ="250000"
```

and 

```
UrlConfig
{
	parentUrl = Kopernicus/Config/System.cfg
	Kopernicus
	{
		name = Kerbol System
		Body
		{
			name = Sun
			identifier = Squad/Sun
			Template
			{
				name = Sun
				removeProgressTree = false
			}
			Properties
			{
				radius = 261600000
				geeASL = 1.74684656100137
				rotationPeriod = 432000
				inverseRotThresholdAltitude = 600000
				timewarpAltitudeLimits = 0 3270000 3270000 6540000 1.308E+07 2.616E+07 5.232E+07 6.54E+07
				navballSwitchRadiusMult = 0.06
				navballSwitchRadiusMultLow = 0.055
				mass = 1.7566296605769E+28
				gravParameter = 1.17237463546902E+18
				ScienceValues
				{
					flyingAltitudeThreshold = 18000
					spaceAltitudeThreshold = 1000000000
				}
			}
```

**Comment by Lisias** [comment] 2023-07-28 01:11
@Starcatcher2009 , this patch will work even better:

```
@Kopernicus:AFTER[SigDim2]
{
	@Body:HAS[#name[*]]
	{
		@Properties
		{
			%mass = #$geeASL$
			@mass *= 9.807

			%radiusSquared = #$radius$
			@radiusSquared != 2

			@mass *= #$radiusSquared$
			@mass /= 6.674e-11

			!radiusSquared = DEL

			%gravParameter = #$mass$
			@gravParameter *= 6.674e-11
		}
	}
}
```

By using `%` before the new values, you are leveraging the execution order of the patch in a way that makes accessing the current values of the editing nodes available for use, without the need to access the ones from the original one.

**Comment by Lisias** [comment] 2023-09-26 06:33
Forgot to close this. User reached me on Forum telling it solved the problem.

**Closed by Lisias** 2023-09-26 06:33 UTC
Labels: support
